---
    name: Spellcheck
    
    on:
      push:
      pull_request:
        types: [opened, reopened]
      workflow_dispatch:
    
    env:
      CI_IMAGE_NAME: 'ghcr.io/cradle8810/aspell'
    
    jobs:
        aspell:
            container:
                image: ghcr.io/cradle8810/aspell
            runs-on: ubuntu-latest
            steps:
    
            - name: Checkout
              uses: actions/checkout@v4

            - name: SpellCheck
              run: |
                find . -name "*.txt" -print0 | \
                xargs -0 -t -I {} sh -c "cat {}| aspell --home-dir=$(pwd) -a " | \
                grep -E '^&'
